// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCt50309LGdYBqghjvm6E4qzqzgAfo6bs',
    appId: '1:830245743790:web:57698b27d038de40e3113f',
    messagingSenderId: '830245743790',
    projectId: 'srec-library-1',
    authDomain: 'srec-library-1.firebaseapp.com',
    storageBucket: 'srec-library-1.appspot.com',
    measurementId: 'G-YT4BSH6SHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinp_-h7J8CcFPkWlMNWsPfIsIHlkDnbk',
    appId: '1:830245743790:android:12e3ba5193273ce0e3113f',
    messagingSenderId: '830245743790',
    projectId: 'srec-library-1',
    storageBucket: 'srec-library-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwN-_mbI0Gg1-0VsORtcWBnlCn5ACXIc',
    appId: '1:830245743790:ios:d688dde63f5a1214e3113f',
    messagingSenderId: '830245743790',
    projectId: 'srec-library-1',
    storageBucket: 'srec-library-1.appspot.com',
    iosClientId: '830245743790-gvs6srtdt2dvdvslv5jrtp5rmi9cdot7.apps.googleusercontent.com',
    iosBundleId: 'com.example.srecLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwN-_mbI0Gg1-0VsORtcWBnlCn5ACXIc',
    appId: '1:830245743790:ios:d688dde63f5a1214e3113f',
    messagingSenderId: '830245743790',
    projectId: 'srec-library-1',
    storageBucket: 'srec-library-1.appspot.com',
    iosClientId: '830245743790-gvs6srtdt2dvdvslv5jrtp5rmi9cdot7.apps.googleusercontent.com',
    iosBundleId: 'com.example.srecLibrary',
  );
}
